# Generated by scripts/render-cask.sh. DO NOT EDIT.
# Run the Update cask workflow to publish a new version.
cask "dnsid" do
  version "2026.09.18-d895014"

  on_macos do
    on_arm do
      sha256 "876ba6c6f152c8423b7e3fcfe87fd6df04aebfb4d35d586341b1da210a101c92"
      url "https://dnsid-prod-cli-binaries.s3.us-east-1.amazonaws.com/cli/#{version}/dnsid_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "627eddd2a273d239c1b48cb60f4cd4a3e75f9ef75e748563e91abdb1b4575f08"
      url "https://dnsid-prod-cli-binaries.s3.us-east-1.amazonaws.com/cli/#{version}/dnsid_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "41ba603a99af10ed5a89b602bbecb98a7d234a25728c99f5a0eec63c8cb9d641"
      url "https://dnsid-prod-cli-binaries.s3.us-east-1.amazonaws.com/cli/#{version}/dnsid_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "67bdfb0b47328940e59b56481a4adcbbc70e56fedc068cb0404fe3e6a7a2cad3"
      url "https://dnsid-prod-cli-binaries.s3.us-east-1.amazonaws.com/cli/#{version}/dnsid_linux_amd64.tar.gz"
    end
  end

  name "dnsid"
  desc "Agent identity management CLI for DNSid"
  homepage "https://dnsid.ai"

  livecheck do
    skip "Published on release."
  end

  binary "dnsid"

  postflight do
    # The binaries are unsigned and un-notarized. Homebrew stamps
    # com.apple.quarantine on staged cask payloads, and Gatekeeper kills a
    # quarantined unsigned Mach-O on first exec. Remove this once the darwin
    # builds are signed and notarized.
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dnsid"]
    end
  end
end
