# Generated by scripts/render-cask.sh. DO NOT EDIT.
# Run the Update cask workflow to publish a new version.
cask "dnsid" do
  version "2026.08.25-22f2882"

  on_macos do
    on_arm do
      sha256 "dee62bd64a0fa1dd05884bce8673c1c806fdebb7b4443da7ef718a6bcb336281"
      url "https://dnsid-prod-cli-binaries.s3.us-east-1.amazonaws.com/cli/#{version}/dnsid_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0f21954f710c1e154ee7e89e4d307230910c922cf203dd8f9274c040136c31c4"
      url "https://dnsid-prod-cli-binaries.s3.us-east-1.amazonaws.com/cli/#{version}/dnsid_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9412785675193f943b1d784a4597ec8100f0e93bc80ce16cafb743ca2f4fa701"
      url "https://dnsid-prod-cli-binaries.s3.us-east-1.amazonaws.com/cli/#{version}/dnsid_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "af58abdf93079ba5ded7cf522e8ce234f15375d8f27c4456ed7fb56d19e33431"
      url "https://dnsid-prod-cli-binaries.s3.us-east-1.amazonaws.com/cli/#{version}/dnsid_linux_amd64.tar.gz"
    end
  end

  name "dnsid"
  desc "Agent identity management CLI for DNSid"
  homepage "https://dnsid.ai"

  livecheck do
    skip "Published on release."
  end

  binary "dnsid"

  postflight do
    # The binaries are unsigned and un-notarized. Homebrew stamps
    # com.apple.quarantine on staged cask payloads, and Gatekeeper kills a
    # quarantined unsigned Mach-O on first exec. Remove this once the darwin
    # builds are signed and notarized.
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dnsid"]
    end
  end
end
