# Generated by scripts/render-cask.sh. DO NOT EDIT.
# Run the Update cask workflow to publish a new version.
cask "dnsid" do
  version "2026.10.02-8e8404f"

  on_macos do
    on_arm do
      sha256 "eae99cb130f6d33ff8ea72437d37dbfc1c01fa912ea9a51353b5add22726dd49"
      url "https://downloads.dnsid.ai/cli/#{version}/dnsid_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7c5a0f49af2c2dcba90444ccfeb684c23b22fc48b143cd77bccda69b6074c228"
      url "https://downloads.dnsid.ai/cli/#{version}/dnsid_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1819c9916ac013ed8bbb5e2b1ce9e289758181d1b03deabde7595b2da5e4ec69"
      url "https://downloads.dnsid.ai/cli/#{version}/dnsid_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "51ad06a4030caf05d5ad0e3ee64afa0981265f003ba6307cca723c9a94eaa0e8"
      url "https://downloads.dnsid.ai/cli/#{version}/dnsid_linux_amd64.tar.gz"
    end
  end

  name "dnsid"
  desc "Agent identity management CLI for DNSid"
  homepage "https://dnsid.ai"

  livecheck do
    skip "Published on release."
  end

  binary "dnsid"

  postflight do
    # The binaries are unsigned and un-notarized. Homebrew stamps
    # com.apple.quarantine on staged cask payloads, and Gatekeeper kills a
    # quarantined unsigned Mach-O on first exec. Remove this once the darwin
    # builds are signed and notarized.
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dnsid"]
    end
  end
end
