#!/usr/bin/env bash
#
# Render Casks/dnsid.rb for a released version of the dnsid CLI.
#
#   ./scripts/render-cask.sh 2026.08.25-22f2882
#
# Reads SHA256SUMS and the archives from $ARTIFACT_BASE/<version>/, and writes
# the cask. Does not commit — the workflow does that, and running this locally
# leaves a diff you can inspect.
#
# Fails closed at every step. A cask that references an archive that is not
# there, or whose checksum we could not read, is worse than no update at all:
# Homebrew would surface it to users as a broken install of a version that
# looks published.

set -euo pipefail

VERSION="${1:-}"
if [ -z "$VERSION" ]; then
  echo "usage: $0 <version>   e.g. $0 2026.08.25-22f2882" >&2
  exit 2
fi

# The one place the download host is stated. When dnsid moves to dnsid-ai and
# its release assets become public, point this at
# https://github.com/dnsid-ai/dnsid/releases/download — the path shape
# (<base>/<version>/<file>) is the same, so nothing else changes.
ARTIFACT_BASE="${ARTIFACT_BASE:-https://dnsid-prod-cli-binaries.s3.us-east-1.amazonaws.com/cli}"

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TEMPLATE="$REPO_ROOT/templates/dnsid.rb.tmpl"
OUTPUT="$REPO_ROOT/Casks/dnsid.rb"

# Only the archives the cask actually references. The windows zip is published
# but not served through Homebrew.
ARCHIVES=(
  dnsid_darwin_arm64.tar.gz
  dnsid_darwin_amd64.tar.gz
  dnsid_linux_arm64.tar.gz
  dnsid_linux_amd64.tar.gz
)

die() { echo "error: $*" >&2; exit 1; }

echo "version:  $VERSION"
echo "base:     $ARTIFACT_BASE"

SUMS="$(curl -fsSL "$ARTIFACT_BASE/$VERSION/SHA256SUMS")" \
  || die "no SHA256SUMS for $VERSION at $ARTIFACT_BASE. Either the version is wrong, or the release never uploaded its artifacts."

# Confirm every archive is actually there. SHA256SUMS existing does not prove
# the archives beside it do — releases have been tagged with no artifacts
# behind them.
for archive in "${ARCHIVES[@]}"; do
  url="$ARTIFACT_BASE/$VERSION/$archive"
  curl -fsSL -o /dev/null -r 0-0 "$url" \
    || die "$archive is not downloadable at $url"
done

sha_for() {
  local want="$1" sha
  sha="$(printf '%s\n' "$SUMS" | awk -v f="$want" '$2 == f { print $1 }')"
  [ -n "$sha" ] || die "SHA256SUMS has no entry for $want"
  printf '%s\n' "$sha" | grep -Eq '^[0-9a-f]{64}$' \
    || die "checksum for $want is not a sha256 digest: $sha"
  printf '%s' "$sha"
}

mkdir -p "$(dirname "$OUTPUT")"

{
  echo "# Generated by scripts/render-cask.sh. DO NOT EDIT."
  echo "# Run the Update cask workflow to publish a new version."
  sed \
    -e "s|@VERSION@|$VERSION|g" \
    -e "s|@ARTIFACT_BASE@|$ARTIFACT_BASE|g" \
    -e "s|@SHA_DARWIN_ARM64@|$(sha_for dnsid_darwin_arm64.tar.gz)|g" \
    -e "s|@SHA_DARWIN_AMD64@|$(sha_for dnsid_darwin_amd64.tar.gz)|g" \
    -e "s|@SHA_LINUX_ARM64@|$(sha_for dnsid_linux_arm64.tar.gz)|g" \
    -e "s|@SHA_LINUX_AMD64@|$(sha_for dnsid_linux_amd64.tar.gz)|g" \
    "$TEMPLATE"
} > "$OUTPUT"

# A leftover placeholder means the template grew a field the script does not
# fill, which would ship a cask Homebrew cannot parse.
if grep -q '@[A-Z_]*@' "$OUTPUT"; then
  grep -n '@[A-Z_]*@' "$OUTPUT" >&2
  die "unsubstituted placeholders remain in $OUTPUT"
fi

echo "wrote:    $OUTPUT"
